// Generated by CoffeeScript 1.7.1
var Dictionary, GRID_SIZE, Grid, OWL2, Player, inRange, inputCallback, isInteger, promptForTile1, promptForTile2, stdin, strToCoordinates;

Dictionary = require('./Dictionary').Dictionary;

Grid = require('./Grid').Grid;

Player = require('./Player').Player;

OWL2 = require('./OWL2').OWL2;

stdin = process.openStdin();

stdin.setEncoding('utf8');

inputCallback = null;

stdin.on('data', function(input) {
  return inputCallback(input);
});

promptForTile1 = function() {
  console.log("첫 번째 타일 좌표를 입력하기 바랍니다.");
  return inputCallback = function(input) {
    if (strToCoordinates(input)) {
      return promptForTile2();
    }
  };
};

promptForTile2 = function() {
  console.log("두 번째 타일 좌표를 입력하기 바랍니다.");
  return inputCallback = function(input) {
    if (strToCoordinates(input)) {
      console.log("타일 교환...완료!");
      return promptForTile1();
    }
  };
};

GRID_SIZE = 5;

inRange = function(x, y) {
  return (0 <= x && x < GRID_SIZE) && (0 <= y && y < GRID_SIZE);
};

isInteger = function(num) {
  return num === Math.round(num);
};

strToCoordinates = function(input) {
  var halves, x, y;
  halves = input.split(',');
  if (halves.length === 2) {
    x = parseFloat(halves[0]);
    y = parseFloat(halves[1]);
    if (!isInteger(x) || !isInteger(y)) {
      return console.log("각 좌표는 정수값이어야 한다.");
    } else if (!inRange(x - 1, y - 1)) {
      return console.log("각 좌표값의 범위는 1에서부터 " + GRID_SIZE + "까지다.");
    } else {
      return {
        x: x,
        y: y
      };
    }
  } else {
    return console.log('입력 형식은 `x, y`이다.');
  }
};

console.log("5x5 단어 게임에 오신 것을 환영합니다!");

promptForTile1();

//# sourceMappingURL=console.map
