// Generated by CoffeeScript 1.7.1
var Player, root;

Player = (function() {
  function Player(name, dictionary) {
    this.name = name;
    if (dictionary != null) {
      this.setDictionary(dictionary);
    }
  }

  Player.prototype.setDictionary = function(dictionary) {
    this.dictionary = dictionary;
    this.score = 0;
    return this.moveCount = 0;
  };

  Player.prototype.makeMove = function(swapCoordinates) {
    var result;
    this.dictionary.grid.swap(swapCoordinates);
    this.moveCount++;
    result = scoreMove(this.dictionary, swapCoordinates);
    this.score += result.moveScore;
    return result;
  };

  return Player;

})();

root = typeof exports !== "undefined" && exports !== null ? exports : window;

root.Player = Player;

//# sourceMappingURL=Player.map
